@ContosoPizza_HostAddress = http://localhost:5249

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/5
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii2",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/4
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

DELETE {{ContosoPizza_HostAddress}}/pizza/3

###